### PR TITLE
Add region attribute to aws_s3_file provider

### PR DESCRIPTION
**Pull request by TaopaiC**
Add region attribute to aws_s3_file provider , ex:

    aws_s3_file "/tmp/foo" do
      bucket "i_haz_an_s3_buckit"
      remote_path "path/in/s3/bukket/to/foo"
      region "cn-north-1"
      aws_access_key_id aws['aws_access_key_id']
      aws_secret_access_key aws['aws_secret_access_key']
    end

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @TaopaiC

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by miketheman** [comment]
I think #115 is something you might want to look at for a a region detector.

**Comment by soem** [comment]
@miketheman 
I'd think the #115 or #160 are not do the same thing with this pull request.
This patch can resolve the issue when fetch files from different AWS region by different AWS key.
(E.g. AWS-CN, AWS China region is totally independence.  You have to use different AWS keypair.)

Have you ever tried the AWS China region?

**Comment by martinisoft** [comment]
I'd love to get this merged before #160 since putting the setting at the LWRP level helps with flexibility of the resource. Having a global default like it's defined in #160 would be good to merge after this patch goes in first.

**Comment by joshzitting** [comment]
This is a great idea and I think it would be the easiest to use. That way you can pull files from different places/regions.

**Comment by djapg** [comment]
+1 on this PR, I'm running into issues accessing files needed for a global deployment

**Comment by timothykibler** [comment]
@joshzitting @SIGUSR2 +1 I have the same use case where I have an s3 bucket in us-east-1 but cannot access it from us-west-1. It doesn't work since the bucket can only be accessed by the s3url without the region appended. I've gotten it to work by just setting the region to us-east-1 in the s3 provider file like in the example but I'm guessing this is a more elegant solution?

**Comment by ngtjah** [comment]
I had a similar issue trying to connect to s3 from my vagrant vm outside of amazon.

```
Errno::EHOSTUNREACH
-------------------
No route to host - connect(2) for "169.254.169.254" port 80
```


This configuration worked for me

```
include_recipe 'aws'

aws_s3_file '/home/nfs-prompts.tar.gz' do
  bucket node['s3_bucket']
  region 'us-west-1'
  remote_path 'releases/audio-nfs/nfs-prompts.tar.gz'
  aws_access_key_id node['aws_access_key']
  aws_secret_access_key node['aws_secret_access_key']
  owner 'root'
  group 'root'
  mode 0644
end
```

Will this patch be added to the main cookbook soon?

**Comment by kmkswamy** [comment]
Any idea when this will be pushed to the master?

**Comment by jemaiah** [comment]
working for me! very useful for downloading a file from S3 from another region, for a worldwide deployment.

**Comment by zl4bv** [comment]
> @miketheman 
> I'd think the #115 or #160 is not doing the same thing with this pull request.
> This patch can resolve the issue when fetch files from different AWS region by different AWS key.

Agreed. Given the attribute is shared across all resources in a chef run, this limits s3 access to a single region. This seems undesirable in situations where you are configuring multiple applications in a single chef run where each application reads from a bucket in a different region.

**Comment by ubiquitousthey** [comment]
Author of #115/#160 here.  This seems like an improvement if will resolve in this order:

1. Region specified on the provider
2. Region specified by attribute
3. Region for ec2 instance
4. Default (or error)

This PR has conflicts at this point.  Does someone want to resolve them with the logic mentioned above?

**Comment by zl4bv** [comment]
As far as `4. Default (or error)` goes, would it be more sensible to default to leaving it undefined? The advantage of leaving it undefined is allowing the AWS SDK to look up the region from its own definition of default locations.

From the [aws-sdk-ruby](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html) documentation:

> You can configure a default region in the following locations:
>
> ENV['AWS_REGION']
> Aws.config[:region]

**Comment by martinisoft** [comment]
I agree with @zl4bv because it will have other default options built-in to fall back to.

**Comment by tas50** [comment]
I like the concept of this PR.  #115 was merged in and then I broke out some of the region logic into it's own method. This will need to get rebased now that both of those changes are in.  If you wanna get it cleaned up to the current state of master I'd love to get it merged in. Also don't forget to document this in the readme.  It would be a shame if we had the functionality and no one knew it was there.

**Comment by tas50** [comment]
This was merged in with #191

**Pull request closed without merging**
