### PR TITLE
Issue 327 

### PR DESCRIPTION
**Pull request by chefbob**
### Description

Added get functionality for AWS Systems Manager Parameter Store

### Issues Resolved

Issue 327

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by chefbob** [comment]
2nd try at pull request. This should have a correct DCO

**Comment by tas50** [comment]
Looks like you nuked the work out in the PR by accident

**Comment by chefbob** [comment]
@tas50 I'm still learning git.  It's still here, https://github.com/chef-cookbooks/aws/pull/333.  Is there a way to retrieve it?

**Comment by tas50** [comment]
Unfortunately unless you have a copy of the branch or repo somewhere you can't retrieve it once you do the push. It might be easier at this point to reset everything and create a fresh PR with the changes signed off from the start.  Sorry this is such a pain. Git isn't always the easiest.

**Pull request closed without merging**
