### PR TITLE
adding delete_on_termination attribute for ebs_volume (Issue #167)

### PR DESCRIPTION
**Pull request by nsdavidson**
Adding the ability to set the delete_on_termination attribute on ebs_volume resources, addressing #167.

### CODE REVIEW

**Comment by scalp42** [comment]
:+1:

**Comment by vanwho** [comment]
:+1:  this addition will be great
rebase so no more conflicts and they can merge easily?

**Comment by nsdavidson** [comment]
Rebased against master.

**Comment by scalp42** [comment]
thanks @nsdavidson  !

cc @tas50 maybe :pray:

**Comment by tas50** [comment]
I'm currently up in Seattle for Chef team meetings.  This is certainly one of our high priority cookbooks and I need to get setup for some thorough testing.  I'm hoping that in the next few weeks some large scale merging gets done here.

**Comment by tas50** [comment]
Looks good to me.  I'm going to remove the super part though since default_action handles that natively

def initialize(*args)
  super
  @action = :create
end

**Pull request merged**
