### PR TITLE
Adjust Gem Dependency to use individual aws-sdk v3 gems

### LINKED ISSUE #355: ChefDK issue with aws-sdk gem
Hi folks,

I'm not sure if the issue should be opened here on in ChefDK repo.

I've set up two kitchen suites with logs here: https://github.com/scalp42/chefdk-aws-issue

The example is a simple recipe installing `aws-sdk-kms` v3 and module requiring `aws-sdk-kms` (but any other aws gem will break I'm pretty sure):

```ruby
module Kitchen
  def self.test!
    require 'aws-sdk-kms'

    Chef::Log.info 'It works! YAY'
  end
end
```

If using the product `chef`, then everything will work as expected when the module method is called:

```
     Installing Cookbook Gems:
       Compiling Cookbooks...
       Recipe: chefdk-aws-issue::default
         * chef_gem[aws-sdk-kms] action install[2018-06-13T22:03:39+00:00] INFO: Processing chef_gem[aws-sdk-kms] action install (chefdk-aws-issue::default line 10)
       [2018-06-13T22:03:40+00:00] INFO: chef_gem[aws-sdk-kms] installed aws-sdk-kms at 1.5.0

           - install version 1.5.0 of package aws-sdk-kms
       [2018-06-13T22:03:41+00:00] INFO: It works! YAY
         Converging 1 resources
         * chef_gem[aws-sdk-kms] action install[2018-06-13T22:03:41+00:00] INFO: Processing chef_gem[aws-sdk-kms] action install (chefdk-aws-issue::default line 10)
        (up to date)
       [2018-06-13T22:03:41+00:00] INFO: Chef Run complete in 2.159324895 seconds
```

If using the product `chefdk`, then it'll error out with following error:

```
         Gem::ConflictError
         ------------------
         Unable to activate aws-sdk-kms-1.5.0, because aws-sdk-core-2.11.50 conflicts with aws-sdk-core (~> 3)

         Cookbook Trace:
         ---------------
           /var/tmp/kitchen/cache/cookbooks/chefdk-aws-issue/libraries/aws.rb:3:in `test!'
           /var/tmp/kitchen/cache/cookbooks/chefdk-aws-issue/recipes/default.rb:14:in `from_file'

         Relevant File Content:
         ----------------------
         /var/tmp/kitchen/cache/cookbooks/chefdk-aws-issue/libraries/aws.rb:

           1:  module Kitchen
           2:    def self.test!
           3>>     require 'aws-sdk-kms'
           4:
           5:      Chef::Log.info 'It works! YAY'
           6:    end
           7:  end
           8:

         System Info:
         ------------
         chef_version=14.1.12
         platform=ubuntu
         platform_version=16.04
         ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
         program_name=/opt/chefdk/bin/chef-client
         executable=/opt/chefdk/bin/chef-client
```

The only difference on fresh install is that `ChefDK` has `aws-sdk` v2 already installed:

```
root@default-ubuntu-1604:~# /opt/chefdk/bin/chef --version
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72

root@default-ubuntu-1604:~# /opt/chefdk/embedded/bin/gem list | grep 'aws-sdk'
aws-sdk (2.11.50)
aws-sdk-core (2.11.50)
aws-sdk-resources (2.11.50)
```

It may or may not be related to https://github.com/chef-cookbooks/aws/issues/323.

TLDR: when requiring `aws-sdk-kms` v3, Chef works fine but ChefDK breaks.

Thanks for the help in advance 🤕

cc @tas50

### PR DESCRIPTION
**Pull request by bdwyertech**
### Description

The gem `aws-sdk` installs a plethora of AWS gems, one for each service.  Rather than do this, limit the scope to only the gems which this cookbook's functionality depend on.

Please reference the gem [`aws-sdk-resources`](https://github.com/aws/aws-sdk-ruby/blob/05bb9358240923d2831aeb206f1b51eb41db81f3/gems/aws-sdk-resources/lib/aws-sdk-resources.rb) to see the break-out pattern for `aws-sdk` gem.

### Issues Resolved

Should resolve a bunch of issues seen on Windows with regard to native extension compilation and OOM conditions resulting from compilation of gems otherwise not used by this cookbook.

#355 - Probably not... looks like aws-sdk-kms still gets installed as part of something.

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
I'm sure this is going to have to unintended consequences but it's time to do it.

**Comment by bdwyertech** [comment]
Yeah. This cookbook is kind of a mess @tas50, I should be able to clean up some of the resources my company uses.

**Comment by tas50** [comment]
It's been death by 1000 patches for sure. I'd appreciate any fixes you might have.

**Comment by bdwyertech** [comment]
You got it.  Do me a favor and if you're gonna cut a release, go up a minor or major. I made a hot patch with this fix at 7.5.1 internally.... :-/

**Comment by jakauppila** [comment]
@bdwyertech @tas50 I'm curious what both of your perspectives are on how gem dependencies should be managed in this cookbook as far as AWS releasing new versions of the gems all the time.

For reference: https://github.com/chef/chef/issues/7636

Should this cookbook be pinning to prevent such a problem from incurring?

**Pull request merged**
