### PR TITLE
s3_file to a custom resource and move modules around

### PR DESCRIPTION
**Pull request by tas50**
Opscode::Aws is now AwsCookbook
s3_file is now a custom resource
Unnecessary libraries are now just included in the resources themselves

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
regex errors will be resolved when we get the latest cookstyle in DK

**Comment by lamont-granquist** [comment]
renaming the modules will most likely be a major breaking change for some users -- i think people have mixed those directly into their stuff and used them directly.

**Comment by tas50** [comment]
@lamont-granquist Moving stuff out of those modules and renaming them is breaking. I'm moving this away from an aws helper library cookbook to a cookbook of resources only. Most of the helpers were not actually very helpful. They're from the days before the ec2 ohai plugin actually worked

**Comment by lamont-granquist** [comment]
yeah that makes  sense

**Pull request merged**
