### PR TITLE
Added spec/recipes.

### PR DESCRIPTION
**Pull request by xacaxulu**
Added Gemfile.
Updated Berksfile 'site' to 'source' per deprecation warning.
Added default_spec.rb to bring ChefSpec::Coverage to 100%
Specs passing.

### CODE REVIEW

**Comment by miketheman** [comment]
This looks awesome! Thanks @xacaxulu - this is a :+1: from me.

**Comment by miketheman** [comment]
@xacaxulu Can I ask you to rebase on master? A few things have been fixed in individual commits.

**Comment by xacaxulu** [comment]
@miketheman I think I correctly fetched upstream and rebased master. Please ping me if I derped it up.

**Comment by miketheman** [comment]
@xacaxulu Looks like a merge, not a rebase. You might want to try `git rebase --interactive upstream/master` or the like.

**Comment by xacaxulu** [comment]
Hi @miketheman. If I've sufficiently borked this one up, feel free to decline and I'll submit a new clean PR. My git fu is weak on fork collab stuff :/

**Comment by miketheman** [comment]
@xacaxulu Don't sweat it - I'll rebase and whatnot prior to merging. Thanks!

**Comment by tas50** [comment]
I pulled this change in with https://github.com/chef-cookbooks/aws/commit/45778269e1a9f5a4c2de538b36bf71ac70c2a7a3

Thanks for helping us add to the testing

**Pull request closed without merging**
