### PR TITLE
Added ability to upload files to S3

### PR DESCRIPTION
**Pull request by hntd187**
I added another LWRP to upload files to S3 as well. Hopefully someone finds this useful.

### CODE REVIEW

**Comment by miketheman** [comment]
This has been superseded by ae948c9d61924e35da56f85c54859cb00f7d24c8 - recommend closure.

**Comment by bmhatfield** [comment]
@miketheman - it appears that the commit you reference does not actually supersede this. The intent of this PR is to upload *to* s3, but your link only supports downloading *from*. Thoughts on this?

**Comment by miketheman** [comment]
@bmhatfield That's a good point. I think I may have closed prematurely.

I think this could be expressed under the current `aws_s3_file` resource, instead of adding another interface - especially since this library no longer uses the right_aws library.

**Comment by hntd187** [comment]
@miketheman I could update this pull request as per your suggestions if that would help?

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by miketheman** [comment]
@hntd187 That would be a great idea, thanks!

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by charj-it** [comment]
Is it possible to put files using a similar method to this?

**Comment by iennae** [comment]
Please make sure to sign the CLA: https://supermarket.chef.io/become-a-contributor

**Comment by hntd187** [comment]
@iennae I'm fairly certain I signed it. My profile is here on the supermarket https://supermarket.chef.io/users/scarman

**Comment by iennae** [comment]
Awesome! thanks @hntd187. looks like maybe email addresses are differing between github and chef. We'll take a look at this next week. Thanks!

**Comment by tas50** [comment]
@hntd187 I agree with @miketheman that we should include this in the existing s3_file LWRP as an :upload action.

**Comment by donaldgifford** [comment]
Hi, any chance this ever gets merged in?

**Comment by tas50** [comment]
I'm going to close this out as an individual provider for the upload functionality is not the right way to go.  This should be a :put action on the existing s3_file functionality.  Additionally we need to be able to support more than key based authentication in the provider. We're support a slew of auth methods now that we need to be able to use with this new action. Feel free to rework this and open it back up as an action in the existing provider.

**Pull request closed without merging**
