### PR TITLE
Modified find_snapshot_id method to make it work as intended

### LINKED ISSUE #214: EBS Volume from other volume does not obey most_recent_snapshot
I'm creating an EBS volume by using a volume ID as the initial snapshot_id in the resource. Even with most_recent_snapshot set to true, the oldest snapshot is always used.

aws_ebs_volume 'aem_ebs_volume' do
    size 1000
    device '/dev/sdi'
    volume_type 'gp2'
    most_recent_snapshot true
    action [:create, :attach]
    snapshot_id 'vol-a1b2c3d4'
end

Any ideas?

### PR DESCRIPTION
**Pull request by darwin67**
### Description

Fixes the issue that `aws_ebs_volume` will not grab the most recent snapshot even when passed with `true` to the `most_recent_snapshot` attribute.

### Issues Resolved

#214 

### Details
the `:snapshots` hash key or `snapshots` method is required to access the snapshots from the response. However, that part was missing which results in the array not getting sort.
[FYI](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_snapshots-instance_method)

Please see screenshots for details
**without hash key or method call**
without_hash_prefix

**with hash key**
with_hash_prefix

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @darwin67

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by darwin67** [comment]
not sure what this test failure is about...

**Comment by darwin67** [comment]
Is this test failure related to my changes?

**Comment by tas50** [comment]
The failure isn't related.  Thanks for getting this fixed. I'll get it released.

**Pull request merged**
