### PR TITLE
Use attribute for region if not in ec2

### PR DESCRIPTION
**Pull request by ubiquitousthey**

### CODE REVIEW

**Comment by martinisoft** [comment]
Did you want to keep this separate from #115 or close that one in favor of this PR? Would love to see this get merged so I can unpin my much older cookbook. :+1:

**Comment by ubiquitousthey** [comment]
This is a squashed version of #115.  I'll close it.

**Comment by ubiquitousthey** [comment]
I, and others, would love to see this in milestone:2.7.2.

**Comment by miketheman** [comment]
Thanks! I've tagged for the 2.8.0 release, which will include enhancements and features. 2.7.2 has been released already.

Side note: I think we definitely need to take a stab at adding spec testing to this cookbook, as this has lagged behind due to the remote API complexity, but the newer SDK has some nice stubbing/mocking abilities that should prove worthwhile.

**Comment by joshzitting** [comment]
I have a question on this... 
If we are deploying instances say in us-west-1 but my s3 bucket is in us-west-2 will it screw up all of the outher uses of this cookbook by having this attribute set??? I would sure prefer just to have a variable that I set in the aws_s3_file LWRP for that particular file???

Or will this not be an issue??

**Comment by martinisoft** [comment]
@joshzitting Good point, that solution is being proposed in #149 so I am wondering if we need to merge these solutions together.

Have an attribute default that the LWRP defaults to, but allow for it to be changed with the LWRP defined resource. Otherwise I am in favor of merging #149 first then changing this solution to add that.

**Comment by SIGUSR2** [comment]
+1 @joshzitting  @martinisoft ... fits exactly the way I use this resource

**Comment by rojomisin** [comment]
do we know which version of the cookbook introduced this?  2.5.0 seems to be ok, 2.7.2 has this bug.

**Comment by martinisoft** [comment]
@rojomisin Version 2.6.0 is where they changed the gem which caused the break.

**Comment by davidski** [comment]
As a new user kicking the tires on this cookbook on a local vagrant instance before moving to AWS, hitting the dependency on the instance metadata under the 2.7.x branches is a rude bump. Would dearly love to see this merged and a release cut to supermarket. Thanks!

**Comment by miketheman** [comment]
@tas50 I'm a :+1: on this.

**Pull request merged**
