### PR TITLE
Issue327

### PR DESCRIPTION
**Pull request by chefbob**
### Description

Adds get functionality to aws_ssm_parameter_store

### Issues Resolved

issue 327

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by chefbob** [comment]
I added support to get a parameter from the AWS Systems Manager Parameter Store.  Test cases were added and the readme file was updated and includes examples.  I didn't add the test cases to the .kitchen.yml file because the ec2 instance role may require some policy changes in order to be able to access the parameter store.

**Comment by chefbob** [comment]
I'm struggling with the DCO.  I commit my changes with -s and I see the signoff in the commit by sometimes the DCO says it hasn't been signed off.  I'm not sure why.

**Comment by iennae** [comment]
@chefbob if you look at https://github.com/chef-cookbooks/aws/pull/333/commits you can see which commits were not signed with the DCO. Try amending the commit to sign the ones that weren't signed originally.

**Comment by chefbob** [comment]
I merged this into another issue 327 pull request with the correct DCO.  I'm going to close this pull request.

**Pull request closed without merging**
