### PR TITLE
Lock aws gems to their latest minor version to prevent huge numbers of gems being installed

### PR DESCRIPTION
**Pull request by majormoses**
### Description

Locking aws gems to their latest minor version. This should make it so that only newly released patches for the respective aws gems are installed by default. This is because aws has a bunch of gems that release daily, this causes hundreds of versions of the same gems to be installed. In our scenerio at work just including the cookbook and making a single ssm call resulted in installing hundreds of gems (which some of the versions left it non functional and looking for shared object files that did not exist. We tried rebuilding the gems via `--pristine` and only after going a `gem --cleanup` did we see any improvement. After doing a cleaned our converge time went from `6 min 04 sec` to `18 sec`.

### Issues Resolved

none, can open if needed.

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by majormoses** [comment]
We can do that as well to some extent, would you be good with just the `aws-*` dependencies or are you looking for all dependencies?

**Comment by jakauppila** [comment]
Yeah, I think that would be fine otherwise that dependency count could continue to grow.

It'd be great if there was some way to generate a gemlock file for all of your cookbooks so you had confidence that something I ran today runs the same in 6 months if there were no other changes to the cookbooks.

**Comment by majormoses** [comment]
I ran the first commit for several hours today in multiple environments today and it seems to be working. I can't say we use all the resources but we use `ssm`, `elb`, and some `iam` resources.

**Comment by jakauppila** [comment]
We only use the `s3_file` resource which is why we ended up forking and stripping so we don't have all those additional dependencies for such a small fraction of functionality.

**Comment by majormoses** [comment]
Ya that makes sense.

**Comment by majormoses** [comment]
> It'd be great if there was some way to generate a gemlock file for all of your cookbooks so you had confidence that something I ran today runs the same in 6 months if there were no other changes to the cookbooks.

You could create a `Gemfile` and then as part of your release process you could do a bundle and upsert the dependencies based on that. Agreed there should probably be a cleaner solution just thinking outside the box. In your `metadata.rb` you can actually execute ruby code so you could call bundler and dynamically build the list. The code executed in `metadata.rb` is evaluated at upload to the chef server. I know that it used to create a `metadata.json` for you but don't quote me on that, chef has changed a lot since I started using it.

**Pull request merged**
