### PR TITLE
Issue 327

### PR DESCRIPTION
**Pull request by chefbob**
### Description

Added get support for AWS SSM Parameter Store

### Issues Resolved

Issue 327

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by chefbob** [comment]
Cleaned up code based on Cookstyle feedback.

**Comment by zopanix** [comment]
+1

**Comment by AkhterAli** [comment]
+1

**Comment by scalp42** [comment]
@tas50 any chance to look a this? 🙏

**Comment by tas50** [comment]
Interesting way to accomplish it. Thanks for putting this together. Sorry for the slow merge. I’ll get it pushed in a release when I’m not on mobile

**Pull request merged**
